#!/bin/sh

#    __               __                  __
#   / /  ___ __    __/ /__ ___  ___ _____/ /__
#  / _ \/ _ `/ |/|/ /  '_// _ \/ _ `/ __/  '_/
# /_.__/\_,_/|__,__/_/\_\/ .__/\_,_/\__/_/\_\
#                       /_/

# File:         bawkpack
# Description:  Packages list installer that SuperB
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/bawkpack
# License:      GPLv3

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Values
list=${1:-$BAWKPACK_LIST}
mainpm=${2:-$BAWKPACK_MAINPM}
[ ! -f "$list"   ] && echo 'Packages list is not found, please `export BAWKPACK_FILE=path/to/packages`' && exit 1
[ ! -n "$mainpm" ] && echo 'main packages manager is unset, please `export BAWKPACK_MAINPM=[Pacman|APT|XBPS]`' && exit 1
bawkpack_cache="${XDG_CACHE_HOME:-"$HOME/.cache"}/bawkpack_cache"
awk '{gsub("#.*$", "");print}' "$list" > "$bawkpack_cache"
	                         pms="$mainpm"
[ "$mainpm"  = 'Pacman' ] && pms="$pms AUR"
	                         pms="$pms Flatpak"
[ "$mainpm" != 'XBPS'   ] && pms="$pms Snapcraft"


# Start
for pm in $pms; do
	if [ -n "$(awk '{print}' "$bawkpack_cache")" ]; then
		case $pm in
			'Pacman')    pm_launcher='sudo pacman --sync --refresh --noconfirm --needed' ; pm_mark='PAC' ;;
			'APT')       pm_launcher='sudo apt install --assume-yes'                     ; pm_mark='APT' ;; #TODO
			'XBPS')      pm_launcher='sudo xbps-install --sync --yes'                    ; pm_mark='XBP' ;;
			'AUR')       pm_launcher='yay -Sy --nodiffmenu --save'                       ; pm_mark='AUR' ;; #FIXME
			'Flatpak')   pm_launcher='sudo flatpak install'                              ; pm_mark='FLA' ;; #FIXME
			'Snapcraft') pm_launcher='sudo snap install'                                 ; pm_mark='SNA' ;; #FIXME
			*)           echo "'$pm' packages manager not found"                         ; exit 1        ;;
		esac

		echo "Installing $pm Packages:"
		$pm_launcher $(awk -v FPAT="$pm_mark:[^ ]+" 'NF{ print $1 }' "$bawkpack_cache" | awk "{gsub(\"$pm_mark:\", \"\");print}")

		awk "!/$pm_mark:/" "$bawkpack_cache" > "$bawkpack_cache"
	fi
done


exit 0
